let remove = "[I recommend to remove this as it might appear not academic or simply useless in your paper]"
let replace = [
    { '(?<!the United States of |North |South |Latin )America\\b': 'the US["America" might be vague. If you mean the country, please replace.]' },
    
    // A
    { 'abundance': 'enough, plenty, a lot' },
    { 'accentuate': 'stress' },
    { 'according to studies': 'studies prove that' },
    { 'acquiesce': 'agree' },
    { 'adjacent': 'next to' },
    { 'admissible': 'allowed, acceptable' },
    { 'advantageous': 'useful,helpful,beneficial' },
    { 'afford an opportunity': 'allow' },
    { 'aforesaid': 'earlier in this document' },
    { 'aggregate': 'total' },
    { 'amalgamation': 'integration' },
    { ', among others?': remove },
    { ', and so on( and so forth)?': remove },
    { 'alleviate': 'ease, reduce' },
    { 'anticipates': 'expects' }, 
    { 'anticipated': 'expected' }, 
    { 'anticipating': 'expecting' }, 
    { 'anticipate': 'expect' },
    { 'apparent': 'clear, plain, obvious' },
    { 'appreciable': 'large' },
    { 'apprise': 'inform, tell' },
    { 'as a consequence of': 'because' },
    { 'as of the date of': 'from' },
    { 'as regards': 'on the subject of' },
    { 'ascertain': 'establish' },
    { 'axiomatic': 'obvious' },
    { 'and also': 'and' },
    { 'appear to be': 'are' },
    { 'appears to be': 'is' },
    { 'appeared to be': 'was' },
    { 'abundance': 'enough or plenty' },
    { 'accede to': 'agree' }, 
    { 'accedes to': 'agrees' }, 
    { 'acceded to': 'agreed' }, 
    { 'acceding to': 'agreeing' },
    { 'ameliorates': 'improves' }, 
    { 'ameliorated': 'improved' },
    { 'ameliorating': 'improving' }, 
    { 'ameliorate': 'improve' },
    
    // B
    { 'become a witness of': 'witness' },
    { 'becomes a witness of': 'witnesses' },
    { 'becoming a witness of': 'witnessing' },
    { 'became a witness of': 'witnessed' },
    { 'by means of': 'by' },
    { 'bring about': 'cause' }, 
    { 'brings about': 'causes' }, 
    { 'brought about': 'caused' }, 
    { 'bringing about': 'causing' },
    { 'By and large,': 'In general' },
    { 'buy':'purchase'},
    { 'buys':'purchases'},
    { 'bought':'purchased'},
    { 'buying':'purchasing'},
    { 'are able to': 'can' }, 
    { 'were able to': 'might' }, 
    { 'was able to': 'could' },
    { 'is able to': 'can' },
    { 'can be able to': 'can' }, 
   
    // C
    { 'could be able to': 'could' },
    { 'chance':'opportunity,possibility'},
    { 'creates':'establishes,conceives,constitutes'},
    { 'created':'established,conceived,constituted'},
    { 'creating':'establishing,conceiving,constituting'},
    { 'create':'establish,conceive,constitute'},
    { 'cognizant': 'aware' },
    { 'commensurate': 'equal' },
    { 'consolidates': 'combines' },
    { 'consolidated': 'combined' }, 
    { 'consolidating': 'combining' }, 
    { 'consolidate': 'combine' },
    { 'compile': 'collect' }, 
    { 'compiles': 'collects' }, 
    { 'compiled': 'collected' }, 
    { 'compiling': 'collecting' },
    { 'component': 'element' },
    { 'comprises': 'includes' },
    { 'construe': 'interpret' },
    { 'costs the sum of': 'costs' },

    // D
    { 'deem to be': 'treat as' },
    { 'deal with': 'handle, manage' },
    { 'deals with': 'handles, manages' },
    { 'dealt with': 'handled, managed' },
    { 'dealing with': 'handling, managing'},
    { 'despite the fact that': 'though, although' },
    { 'detrimental': 'harmful, damaging' },
    { 'disseminate': 'spread' },
    { 'domiciled in': 'living in' },
    { 'drawbacks': 'disadvantages,weaknesses,vulnerabilities' }, 
    { 'drawback': 'disadvantage,weakness,vulnerability' },
    { 'due to': 'as a result of, for the reason that, as a consequence' },
    { 'during which time': 'while' },

    // E
    { 'eligible': 'allowed, qualified' },
    { 'envisage': 'expect, imagine' },
    { 'expedite': 'accelerate' },

    // F
    { 'fights': 'combats,withstands'},
    { 'fought': 'combated,withstood'},
    { 'fighting': 'combating,withstanding'},
    { '(?<!(?:a|the)\\s)fight': 'combat,withstand'},
    { 'finalizes': 'ends, finishes' },
    { 'finalized': 'ended, finished' },
    { 'finalizing': 'ending, finishing' },
    { 'finalize': 'end, finish' },
    { 'first and foremost': 'first' },
    { 'for the duration of': 'during, while' },
    { 'for the purpose of': 'to, for' },
    { 'for the sake of': 'for' },

    // G
    { 'gives':'provides,supplies,presents'},
    { 'gave':'provided,supplied,presented'},
    { 'giving':'providing,supplying,presenting'},
    { 'give':'provide,supply,present'},
    { 'give consideration to': 'consider' },

    {'get well':'recover'},
    {'gets well':'recovers'},
    {'getting well':'recovering'},
    {'got well':'recovered'},

    // H
    { 'happens':'occurs'},
    { 'happened':'occurred'},
    { 'happening':'occurring'},
    { 'happen':'occur'},
    { 'have been able to':'could'},
    { 'henceforth': 'from now on, from today' },
    { 'he/she': 'he or she' },
    { 'his/her': 'his or her' },
    { 'him/her': 'him or her' },
    { 'his/her': 'his or her' },
    { 'help':'assist'},
    { 'helps':'assists'},
    { 'helped':'assisted'},
    { 'helping':'assisting'},
    { 'hereby': 'now, by this' },
    { 'herein': 'here' },
    { 'hereinafter': 'after this' },
    { 'hereof': 'of this' },
    { 'hereto': 'to this' },
    { 'heretofore': 'until now, previously' },
    { 'hereunder': 'below' },
    { 'herewith': 'with this' },
    { 'hitherto': 'until now' },
    { 'hold in abeyance': 'wait, postpone' },
    { 'hope and trust': 'hope, trust' },
    { 'humankind': 'humanity' },
    { 'huge':'enormous,massive,considerable'},
   
    // I
    { 'if when': 'if,when' },
    { 'in a bid': 'in attempt' },
    { 'in conjunction with': 'and, with' },
    { 'in connection with': 'for' },
    { 'in lieu of': 'instead of' },
    { '(?<=\\.\\s)In the end': 'Finally' },
    { 'in a nutshell': 'to summarize' },
    { 'cheap': 'inexpensive' },
    { 'smart': 'intelligent' },
    { 'in order to': 'to' },
    { 'in the event( that)?': 'if' },
    { 'in the near future': 'soon' },
    { 'in the neighborhood of': 'around' },
    { 'in view of the fact that': 'as,because' },
    { 'irrespective of': 'despite, even if' },

    // J
    { 'jeopardize': 'risk, threaten' },
    
    // K
    { 'keep': 'retain' },
    { 'keeps': 'retains' },
    { 'kept': 'retained' },
    { 'keeping': 'retaining' },

    // L
    { 'lets': 'permits' },
    { 'letting': 'permitting' },
    { 'let': 'permit' },
    { 'look at': 'consider' },
    { 'looks at': 'considers' },
    { 'looked at': 'considered' },
    { 'looking at': 'considering' },
    

    // M
    { 'mad':'insane'},
    { 'mankind': 'humanity[Use gender inclusive language]' },
    { 'make it easier': 'facilitate' },
    { 'makes it easier': 'facilitate' },
    { 'made it easier': 'facilitated' },
    { 'making it easier': 'facilitating' },
 
    { 'make it easy': 'facilitate' },
    { 'makes it easy': 'facilitate' },
    { 'made it easy': 'facilitated' },
    { 'making it easy': 'facilitating' },

    { 'make it possible': 'allow' },
    { 'makes it possible': 'allows' },
    { 'made it possible': 'allowed' },
    { 'making it possible': 'allowing' },

    { 'make use of': 'benefit from' },
    { 'makes use of': 'benefits from' },
    { 'made use of': 'benefited from' },
    { 'making use of': 'benefitting from' },

    { 'make a difference': 'differentiate, distinguish' },
    { 'makes a difference': 'differentiates, distinguishes' },
    { 'made a difference': 'differentiated, distinguished' },
    { 'making a difference': 'differentiating, distinguishing' },

    { 'make it clear': 'clarify' },
    { 'makes it clear': 'clarifies' },
    { 'making it clear': 'clarifying' },
    { 'made it clear': 'clarified' },

    { 'make sure': 'ensure' },
    { 'makes sure': 'ensures' },
    { 'making sure': 'ensuring' },
    { 'made sure': 'ensured' },
    { 'magnitude': 'size' },
    { 'making sure': 'ensuring' }, { 'makes sure': 'ensures' }, { 'made sure': 'ensured' }, { 'making sure': 'ensuring' },
    { 'may in the future': 'may, might, could' },
    { 'mess':'disorder,chaos,clutter'},
    { 'might be able to': 'might' }, 
    { 'more so': 'moreover' }, 


    // N
    
    // O
    { 'occasioned by': 'caused by, because of' },
    { 'on a regular basis': 'regularly' },
    { 'on the grounds that': 'because' },
    { 'on the occasion that': 'when, if' },
    { '(?<!(?:years? |-))\\bold\\b(?!-)':'elderly,ancient,aged'},
    
    // P
    { 'partially': 'partly' },
    { 'particulars': 'details, facts' },
    { 'per annum': 'a year' },
    { 'per cent': 'percent' },
    { 'persons': 'individuals,people' },
    { 'person being interviewed': 'interviewee' },
    { 'prior to': 'before' },
    { 'problems': 'issues' },
    { 'problem': 'issue' },
    { 'procure': 'obtain, arrange' },
    { 'profusion of': 'plenty, too many' },
    { 'projected': 'estimated' },
    { 'prolonged': 'long' },
    { 'promptly': 'quickly, at once' },
    { 'promulgate': 'advertise, announce' },
    { 'proximity': 'near' },


    // R
    { 'reiterate': 'repeat, restate' },
    { 'remittance': 'payment' },
    { 'sometimes': 'occasionally' },
    
    // S
    { 'saying': 'stating,arguing,claiming' },
    { 'says': 'states,argues,claims' },
    { 'said': 'stated,argued,claimed' },
    { 'say': 'state,argue,claim' },
    { 'scrutinize': 'study, research' },
    { 'slowly': 'gradually' },
    { 'solely': 'only' },
    { 'some of the': 'some' },
    { 'so as to': 'to' },
    { 'seems': 'appears' },
    { 'seemed': 'appeared' },
    { 'seemingly': 'apparently' },
    { 'seeming': 'appearing' },
    { 'seem': 'appear' },
    { 'smart': 'intelligent' },
    { 'small': 'insignificant,slight,limited'},
    { 'staff': 'personnel,employees' },

    // T
    { 'take place': 'occur' },
    { 'took place': 'occurred' },
    { 'takes place': 'occurs' },
    { 'taking place': 'occurring' },
    { 'take( \\w+)? into consideration': 'consider' },
    { 'took( \\w+)? into consideration': 'considers' },
    { 'takes( \\w+)? into consideration': 'considered' },
    { 'taking( \\w+)? into consideration': 'considering' },
    { 'talk about': 'discuss' },
    { 'talks about': 'discusses' },
    { 'talking about': 'discussing' },
    { 'the question as to whether': 'whether' },
    { 'thereafter': 'then, afterwards' },
    { 'tertiary institutions': 'higher education institutions' },
    { 'tertiary institution': 'higher education institution' },
    { 'told (<span>)?about(</span>)?': 'narrated,discussed,notified' },
    { 'tells': 'informs,notifies,narrates' },
    { 'told': 'informed,notified,narrated' },
    { 'telling': 'informing,notifying,narrating' },
    { 'tell': 'inform,notify,narrate' },
    { 'too(?!\\.|\\,)':'excessively,extremely'},
    { 'tough':'difficult,resilient'},
    { 'to the extent that': 'if, when' },

    // U
    { 'until such time': 'until' },
    { 'utilize': 'use' },
    { 'utilizes': 'uses' },
    { 'utilized': 'used' },
    { 'utilizing': 'using' },

    // V

    // W
    { 'wants':'prefers,requires,desires'},
    { 'wanted':'preferred,required,desired'},
    { 'wanting':'preferring,requiring,desiring'},
    { 'want':'prefer,require,desire'},

    { 'whensoever': 'when' },
    { 'will be able to': 'could' },
    { 'whether or not': 'whether' },
    { 'with a view to': 'to, so that' },
    { 'with effect from': 'from' },
    { 'with reference to': 'regarding' },
    { 'with regard to': 'regarding' },
    { 'with the aim of': 'to' },
    { 'with the minimum of delay': 'quickly' },
    { 'works together':'collaborates'},
    { 'worked together':'collaborated'},
    { 'working together':'collaborating'},
    { 'work together':'collaborate'},


    // Weak Word
    { 'important': 'significant, essential, crucial' },
    { 'interesting': 'amusing, attractive, engaging' },
    { 'show': 'suggest,offer,demonstrate' },
    { 'shows': 'suggests,offers,demonstrates' },
    { 'showed': 'suggested,offered,demonstrated' },
    { 'showing': 'suggesting,offering,demonstrating' },

    { 'good': 'positive,valuable,satisfactory' },
    { 'bad': 'negative,poor,wretched' },
    { 'bigger' : 'massive,more considerable,larger'},
    { 'biggest' : 'largest,colossal,most substantial'},
    { 'big' : 'considerable,large,extensive'},
    { 'happy': 'optimistic,satisfied,glad' },
    { 'unhappy': 'pessimistic,frustrated,disappointed' },
    { 'greatly': 'excellently,positively,considerably' },
    { 'great': 'excellent,prominent,considerable' },
    { 'quite': 'fairly,rather,reasonably' },
    { 'very': 'noticeably,highly,profoundly' },
    { 'tries': 'attempts,struggles,endeavours' },
    { 'tried': 'attempted,struggled,endeavoured' },
    { 'trying': 'attempting,struggling,endeavouring' },
    { 'try': 'attempt,struggle,endeavour' },
    { 'just': 'barely,only,hardly' },
    { 'like': 'such as,similar to,prefer' },
    { 'little': 'insignificant,insufficient,small' },
    { 'give': 'provide,present,transfer' },
    { 'serious': 'severe,significant,difficult' },
    { 'ways': 'approaches,methods,means' },
    { 'way': 'approach,method,manner' },
    { '(?<!the |their |his |her |my |its )right(?! to| for|-)': 'correct,appropriate,suitable[Weak word. Consider replacing]' },
    { 'wrong': 'incorrect,inappropriate,unsuitable' },



    // Short Forms
    { 'don’t': 'do not' },
    { 'doesn’t': 'does not' },
    { 'didn’t': 'did not' },
    { 'aren’t': 'are not' },
    { 'it’s': 'it is' },
    { 'that’s': 'that is' },
    { 'isn’t': 'is not' },
    { 'won’t': 'will not' },
    { 'couldn’t': 'could not' },
    { 'could’ve': 'could have' },
    { 'shouldn’t': 'should not' },
    { 'should’ve': 'should have' },
    { 'wouldn’t': 'would not' },
    { 'would’ve': 'would have' },
    { 'can’t': 'cannot' },
    { 'aren’t': 'are not' },
    { 'wasn’t': 'was not' },
    { 'weren’t': 'were not' },
    { 'hasn’t': 'has not' },
    { 'hadn’t': 'had not' },
    { 'there’s': 'there is' },
    { 'here’s': 'here is' },
    { 'he’s': 'he is' },
    { 'he’ll': 'he will' },
    { 'he’d': 'he would' },
    { 'she’s': 'she is' },
    { 'she’ll': 'she will' },
    { 'she’d': 'she would' },
    { 'they’ll': 'they will' },
    { 'they’d': 'they would' },
    { 'they’re': 'they are' },
    { 'they’ve': 'they have' },
    { 'i’m': 'I am' },
    { 'i’ve': 'I have' },
    { 'i’ll': 'I will' },
    { 'i’d': 'I would' },
    { 'wanna': 'want to' },
    { 'gonna': 'going to' },
    { 'gotto': 'have to' },
    { "don't": "do not" },
    { "doesn't": "does not" },
    { "didn't": "did not" },
    { "aren't": "are not" },
    { "it's": "it is" },
    { "that's": "that is" },
    { "isn't": "is not" },
    { "won't": "will not" },
    { "couldn't": "could not" },
    { "could've": "could have" },
    { "shouldn't": "should not" },
    { "should've": "should have" },
    { "wouldn't": "would not" },
    { "would've": "would have" },
    { "can't": "cannot" },
    { "aren't": "are not" },
    { "wasn't": "was not" },
    { "weren't": "were not" },
    { "hasn't": "has not" },
    { "hadn't": "had not" },
    { "there's": "there is" },
    { "here's": "here is" },
    { "won't": "will not" },
    { "he's": "he is" },
    { "he'll": "he will" },
    { "he'd": "he would" },
    { "she's": "she is" },
    { "she'll": "she will" },
    { "she'd": "she would" },
    { "they'll": "they will" },
    { "they'd": "they would" },
    { "they're": "they are" },
    { "they've": "they have" },
    { "i'm": "I am" },
    { "i'll": "I will" },
    { "i've": "I have" },
    { "i'd": "I would" },

    // British
    { "acknowledgement" : "acknowledgment" },
    { 'aeroplane': 'airplane' },
    { 'aeroplanes': 'airplanes' },
    { 'aluminium': 'aluminum' },
    { 'amongst': 'among' },
    { 'amidst': 'amid' },
    { 'apologise': 'apologize' },
    { 'apologises': 'apologizes' },
    { 'behaviourism': 'behaviorism' },
    { 'behaviourist': 'behaviorist' },
    { 'behaviourists': 'behaviorists' },
    { 'behavioural': 'behavioral' },
    { 'behaviours': 'behaviors' },
    { 'behaviour': 'behavior' },
    { 'bin': 'trash can' },
    { 'bins': 'trash cans' },
    { 'car park': 'parking lot' },
    { 'car parks': 'parking lots' },
    { 'cheque': 'check' },
    { 'cheques': 'checks' },
    { 'colour': 'color' },
    { 'colours': 'colors' },
    { 'grey': 'gray' },
    { 'favour': 'favor' },
    { 'favourite': 'favorite' },
    { 'high street': 'main street' },
    { 'harbour': 'harbor' },
    { 'harbours': 'harbors' },
    { 'holiday': 'vocation' },
    { 'holidays': 'vocations' },
    { 'humour': 'humor' },
    { 'neighbour': 'neighbor' },
    { 'neighbours': 'neighbors' },
    { 'neighbourship': 'neighborship' },
    { 'mobile phone': 'cell phone' },
    { 'mobile phones': 'cell phones' },
    { 'motorway': 'highway' },
    { 'motorways': 'highways' },
    { 'moustache': 'mustache' },
    { 'queue': 'line' },
    { 'queues': 'lines' },
    { 'labour': 'labor' },
    { 'learnt': 'learned' },
    { 'odour': 'odor' },
    { 'per cent': 'percent' },
    { 'petrol': 'gas' },
    { 'programme': 'program' },
    { 'programmes': 'programs' },
    { 'postal code': 'zip code' },
    { 'postal codes': 'zip codes' },
    { 'rubbish': 'garbage' },
    { 'rumour': 'rumor' },
    { 'rumours': 'rumors' },
    { 'speciality': 'specialty' },
    { 'sweets': 'candy' },
    { 'takeaway': 'takeout' },
    { 'torch': 'flashlight' },
    { 'torches': 'flashlights' },
    { 'theatre': 'theater' },
    { 'theatres': 'theaters' },




    // Phrasal verbs

    { 'break up': 'separate' },
    { 'breaks up': 'separates' },
    { 'broke up': 'separated' },
    { 'breaking up': 'separating' },

    { 'back up': 'support' },
    { 'backs up': 'supports' },
    { 'backed up': 'supported' },
    { 'backing up': 'supported' },

    { 'come from': 'originate from,have its source in' },
    { 'comes from': 'originates from,has its source in' },
    { 'came from': 'originated from,had its source in' },
    { 'coming from': 'originating from,having its source in' },

    { 'comes back': 'returns' },
    { 'came back': 'returned' },
    { 'coming back': 'returning' },
    { 'come back': 'return' },

    { 'gets back': 'returns' },
    { 'got back': 'returned' },
    { 'getting back': 'returning' },
    { 'get back': 'return' },

    { 'come out': 'appear' },
    { 'comes out': 'appears' },
    { 'came out': 'appeared' },
    { 'coming out': 'appearing' },

    { 'come up with': 'produce, think of, invent' },
    { 'comes up with': 'produces, thinks of, invents' },
    { 'came up with': 'produced, thought of, invented' },
    { 'coming up with': 'producing, thinking of, inventing' },

    { 'finds out':'discovers,observe,notices'},
    { 'found out':'discovered,observed,noticed'},
    { 'finding out':'discovering,observing,noticing'},
    { 'find out':'discover,observe,notice'},

    { 'goes back': 'returns' },
    { 'went back': 'returned' },
    { 'going back': 'returning' },
    { 'go back': 'return' },

    { 'looks after': 'takes care of' },
    { 'looked after': 'took care of' },
    { 'looking after': 'taking care of' },
    { 'look after': 'take care of' },

    { 'carries out': 'conducts' },
    { 'carried out': 'conducted' },
    { 'carrying out': 'conducting' },
    { 'carry out': 'conduct'},

    { 'carries on': 'continues' },
    { 'carried on': 'continued' },
    { 'carrying on': 'continuing' },
    { 'carry on': 'continue' },

    { 'calls off': 'cancels' },
    { 'called off': 'canceled' },
    { 'calling off': 'canceling' },
    { 'call off': 'cancel' },

    { 'goes over': 'discusses' },
    { 'went over': 'discussed' },
    { 'going over': 'discussing' },
    { 'go over': 'discuss' },

    { 'goes back': 'returns' },
    { 'went back': 'returned' },
    { 'going back': 'returning' },

    { 'goes through': 'undergoes,experiences' },
    { 'went through': 'underwent,experienced' },
    { 'going through': 'undergoing,experiencing' },
    { 'go through': 'undergo,experience' },

    { 'gives in': 'surrenders' },
    { 'gave in': 'surrendered' },
    { 'giving in': 'surrendering' },
    { 'give in': 'surrender' },

    { 'picks up': 'lifts, raises' },
    { 'picked up': 'lift, raised' },
    { 'picking up': 'lifting, raising' },
    { 'pick up': 'lift, raise' },
    
    { 'sums up': 'summarizes' },
    { 'summed up': 'summarized' },
    { 'summing up': 'summarizing'},
    { 'sum up': 'summarize' },

    { 'points out': 'notes,indicates,informs' },
    { 'pointed out': 'noted,indicated,informed' },
    { 'pointing out': 'noting,indicating,informing' },
    { 'point out': 'note,indicate,inform' },

    { 'turns down': 'refuses' },
    { 'turned down': 'refused' },
    { 'turning down': 'refusing' },
    { 'turn down': 'refuse' },

    { 'turns up': 'appears,attends,enters' },
    { 'turned up': 'appeared,attended,entered' },
    { 'turning up': 'appearing,attending,entering' },
    { 'turn up': 'appear,attend,enter' },

    { 'counts on': 'relies on' },
    { 'counted on': 'relied on' },
    { 'counting on': 'relying on' },
    { 'count on': 'rely on' },

    { 'put on': 'switch on' },
    { 'puts on': 'switches on' },
    { 'putting on': 'switching on' },

    { 'gets together': 'meets, gathers' },
    { 'got together': 'met, gathered' },
    { 'getting together': 'meeting, gathering' },
    { 'get together': 'meet, gather' },

    { 'comes up against': 'encounters' },
    { 'came up against': 'encountered' },
    { 'coming up against': 'encountering' },
    { 'come up against': 'encounter' },

    { 'put up with': 'tolerate, tolerated' },
    { 'puts up with': 'tolerates' },
    { 'put up with': 'tolerated' },
    { 'putting up with': 'tolerating' },

    { 'get away with': 'escape the consequences of' },
    { 'gets away with': 'escapes the consequences of' },
    { 'got away with': 'escaped the consequences of' },
    { 'getting away with': 'escaping the consequences of' },

    { 'get over': 'recover from' },
    { 'gets over': 'recovers from' },
    { 'got over': 'recovered from' },
    { 'getting over': 'recovering from' },

    { 'get on': 'succeed' },
    { 'gets on': 'succeeds' },
    { 'got on': 'succeeded' },
    { 'getting on': 'succeeding' },

    { 'get by': 'manage' },
    { 'gets by': 'manages' },
    { 'got by': 'managed' },
    { 'getting by': 'managing' },

    { 'make for': 'move towards' },
    { 'makes for': 'moves towards' },
    { 'making for': 'moving towards' },
    { 'made for': 'moved towards' },

    { 'turn down': 'refuse' },
    { 'turns down': 'refuses' },
    { 'turned down': 'refused' },
    { 'turning down': 'refusing' },

    { 'make up': 'invent' },
    { 'makes up': 'invents' },
    { 'made up': 'invented' },
    { 'making up': 'inventing' },

    { 'put up': 'raise, increase' },
    { 'puts up': 'raises, increases' },
    { 'putting up': 'raising, increasing' },

    // Wordiness
    { 'In conclusion,\\s' : remove},
    { 'it is \\w+ to (?:mention|say|note|argue|state|claim|discuss|remind|recall) that ' : remove},
    { 'it is worth \\w+ing that ' : remove},

]

export default replace;