const weasel = [
    
    "at all times",
    "at the end of the day",
    "at the present time",
    'always',
    "never",
    "in all cases",
    "in many cases",
    "in most cases",
    "in some cases",
    'literally',
    'many people say',
    'it is often claimed',
    'a growing body of evidence',
    'critics claim',
    'economists say',
    'researchers have found',
    'it is obvious that',
    'there is no doubt',
    'undoubtedly',
    'as is known',
    'a matter of fact',
    'essentially',
    'virtually',
    'usually',
    'basically',
    'simply',
    'totally',
    "absolutely",
    "almost",
    'maybe',
    'cutting-edge',
    'that being said',
    'could be',
    'everyday',
    'a growing body of evidence',                       
    'it is commonly known',
    'as everyone knows',
    'as everybody knows',
    'experience proves',
    'experience indicates',
    'people say',
    'it stands to reason',
    'some say',
    'some argue',
    'it is known that',
    'it is commonly known that',
    "it is argued that",
    "it is arguable that",
    'anybody',
    'anyone',
    'everybody',
    'everyone',
]
export default weasel