let wordiness = [
    "as a matter of fact",
    "by means of",
    "current trend that",
    "despite the fact that",
    "the manner in which",
    "in such a way that",
    "it (?:can|may|might) be (?:said|concluded|noted|seen|assumed|stated|claimed|argued) that",
    "it has been found out",
    "it has long been known that",
    "it is a fact that",
    "it is safe to (?:say|state|claim|argue) that",
    'it is a clear indication that',
    "it is of immense importance",
    "it is unarguable that",
    'it is worth \\w+ing that ',
    'it is notable that',
    "it had been argued that",
    "it is noteworthy that",
    "it is imperative to",
    "it has long been known that",
    "it is a fact that",
    "it has been found that",
    "it is well known that",
    "it may be said that",
    "it is for this reason that",
    "it should be noted that",
    "it was evident that",
    'it was also noted that',
    "it has been identified that",
    "a sufficient amount of",
    "along the lines of",
    "at the present time",
    "at this point in time",
    "despite the fact that",
    "due to the fact that",
    "during the time that",
    "for the reason that",
    "five consideration to",
    "happens to be",
    "has been proved to be",
    "in close proximity to",
    "in( the)? conclusion, ",
    "in the near future",
    "in the vicinity of",
    "In summary",
    "is in a position to",
    'it is \\w+ to (?:mention|say|note|argue|state|claim|discuss|remind|recall) that ',
    "in a manner that",
    "in the manner that",
    "in a position to",
    "not with standing the fact that",
    "on the basis of",
    'based on the fact that',
    'it is often a case that',
    'have the ability to',
    'has the ability to',
    "provided that",
    "reach a conclusion",
    "serves a function of being",
    "the question as to",
    "the reason is because",
    "to conclude",
    "to sum up",
    "to summarize",
    'until such time as',
    'on a daily basis',
    'on a weekly basis',
    'during the course of',
    'take under consideration',
    'of the opinion to',
    'to make reference to',
    'in the final analysis',
    'there is no doubt that',
    "with reference to",
    "with the exception that",
    "is able to",
    "was able to",
    'were able to',
    'has been able to',
    'have been able to',
    'considered as being',
    'considered to be',
  ]

var arrayLength = wordiness.length

  for (var i=0; i<arrayLength;i++) {
      var capital = wordiness[i][0].toUpperCase()+wordiness[i].slice(1,wordiness[i].length)
      wordiness.push(capital);
  }

export default wordiness;